version: "3.7"

services:
  novi-db:
    image: novi-db
    container_name: novi-db
    build:
      context: ../../1stDay/3-mysql
    ports:
      - "3306:3306"
    networks:
      - back-tier
    environment:
      MYSQL_ROOT_PASSWORD: novi_root_pass

  novi-web-app:
    image: novi-web-app
    container_name: novi-web-app
    build:
      context: ../../1stDay/4-tomcat-app
    depends_on:
      - novi-db
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier

  novi-portainer:
    image: portainer/portainer:latest
    container_name: novi-portainer
    command: --no-auth --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - back-tier

networks:
  back-tier:
  front-tier:

volumes:
  portainer_data:
